### ISSUE TITLE
Wallet is not switching in the UI

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#2264] opened 2023-07-10 15:51 UTC
## Bug description

Switching the wallet is not reflected in the UI

## Environment
Prod

## Steps to reproduce
 1. Open a Safe
 2. Connect a wallet via MM
 3. Switch Account in MM
 4. Observe the account switches correctly in the UI
 5. Disconnect wallet in the UI
 6. Connect to MM again
 7. Switch Account
 8. Observe the account is not switching in the UI

**Comment by Seroxdesign** [comment] 2023-07-20 13:20
- Hello, is anyone working on this issue? If not is there a bounty attached?

**Comment by katspaugh** [comment] 2023-09-05 08:13
Closing as a duplicate of #2479 (it has more info there).

@Seroxdesign there's no bounty for this.

**Closed by katspaugh** 2023-09-05 08:13 UTC
Labels: bug
