### ISSUE TITLE
Burger menu appears on welcome page and accounts page

### ISSUE THREAD

**Issue by jmealy** [safe-global/safe-wallet-web#3971] opened 2024-07-19 08:43 UTC
## Bug description
The burger menu is shown on screens where it should not be shown.

Edit: There was a ticket and PR for this previously but it wasn't fully fixed: #3897

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

## Steps to reproduce
 1. Go to `/welcome/accounts` or `/welcome`
 2. Make the screen width smaller until the burger menu appears in the left of the header bar.

## Expected result
There is no sidebar to show on these screens so the burger menu should not be shown.

## Obtained result
Burger menu appears and redirects between the accounts page and the welcome page

## Screenshots
![image](https://github.com/user-attachments/assets/ac26b21e-af88-4489-b0cb-0e8ba3cc286c)

**Comment by usame-algan** [comment] 2024-07-19 08:56
Looks like #3897 didnt fully fix it.

**Comment by MHarisAshfaq** [comment] 2024-07-27 13:12
I would like to take on the issue. Could you please assign it to me?

**Comment by katspaugh** [comment] 2024-07-28 06:05
@MHarisAshfaq sure, go ahead 🙏

**Comment by MHarisAshfaq** [comment] 2024-08-12 13:14
Hi @katspaugh, I am unable to reproduce this issue. It looks like this is already fixed.
![Screenshot 2024-08-12 at 6 12 20 PM](https://github.com/user-attachments/assets/6cf1152f-5bd5-4e0a-9093-b638c61ea015)

**Comment by katspaugh** [comment] 2024-08-12 13:26
@MHarisAshfaq nice, closing the issue then. :) Thanks for checking!

**Closed by katspaugh** 2024-08-12 13:26 UTC
Labels: bug, good first issue
