### ISSUE TITLE
Proposing a send funds tx with and account connected with WC shows an error

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2853] opened 2023-11-23 03:54 UTC
## Bug description
Connecting with WC (using MM phone app for example) and trying to sign a Send funds tx shows an 422 error.
There is no issue executing a send funds tx or signing an "add owner" tx, the issue is just when a send funds tx is proposed

## Environment
 - Browser: Chrome
 - Wallet: WC (MM phone app)
 - Chain: Sepolia
 - Env: Current Prod v1.22

## Steps to reproduce
 1. Create a safe with one owner you have in a MM phone app. The safe can be a 1/1
 2. Send tokens to the Safe
 3. Create a tx to send funds anywhere
 4. Sign the tx. DO NOT execute it, just propose it
 5. Click "sign" in your phone

## Expected result
The tx is proposed

## Obtained result
An error 422 is shown

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/4ed1a13c-9490-4704-a946-a0f934ba26fc)

**Comment by katspaugh** [comment] 2023-11-23 08:49
Duplicate of #2818.

**Closed by katspaugh** 2023-11-23 08:49 UTC
Labels: bug
