### ISSUE TITLE
Error connecting to the blockchain. Please try reloading the page. Details Invalid MultiSend contract address.

### ISSUE THREAD

**Issue by CheeKeat10** [safe-global/safe-wallet-web#3937] opened 2024-07-12 07:12 UTC
## Bug description
Suspect "@safe-global/safe-deployments" is not latest version:  "1.37.1"(Current version: ^1.36.0")

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to http://47.90.243.134:8000/home?safe=dhobyghaut:0x600ec114d4c7A5F79295D9510DeCbD6286c7ab38

## Expected result
- No popup error
## Obtained result
- Popup Error connecting to the blockchain.

## Screenshots
![image](https://github.com/user-attachments/assets/a88b5ceb-9b82-4874-89a7-19b31f3e1eb2)

**Comment by katspaugh** [comment] 2024-07-12 12:32
This error is coming from https://github.com/safe-global/safe-core-sdk. Looks like there's a mistmatch between the Safe contract version and the MultiSend version.

safe-deployments likely needs to be updated in safe-core-sdk.

Closing because the issue is not in this repo.

**Closed by katspaugh** 2024-07-12 12:32 UTC
Labels: bug
