### ISSUE TITLE
Keystone logo is not seen on "Continue with..."

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3236] opened 2024-02-12 09:11 UTC
## Bug description
Keystone logo is not seen on the "Continue with..." button.

## Environment
 - Browser: Chrome
 - Wallet: Keystone
 - Chain: any

## Steps to reproduce
 1. Go to the Welcome page page
 2. Connect the Keystone wallet

## Expected result

Keystone logo should be visible.

## Obtained result

It blends with the black background.

## Screenshots
<img width="457" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/7df51258-bbe8-4c78-a598-904f231fb6d7">

**Comment by Akhaled19** [comment] 2024-02-21 22:17
Hi @liliya-soroka  
Do you have a preference for the final appearance of the button? If you prefer the button to remain black, I could either add a white box behind the logo or a white stroke around the entire logo.

**Comment by katspaugh** [comment] 2024-02-22 09:57
It would be good to make it look like the Keystone icon in this component:

<img width="818" alt="Screenshot 2024-02-22 at 10 57 09" src="https://github.com/safe-global/safe-wallet-web/assets/381895/db159af7-537b-4139-95c8-dca0b1fcab8f">

**Comment by Akhaled19** [comment] 2024-02-22 21:28
Yes so in dark mode would -> add a gray box behind the logo 
and in light mode -> add a white box behind the logo 
this change should apply to all logos, not just keystone. 
Let me know what you think

**Comment by katspaugh** [comment] 2024-02-22 21:32
In addition to that the logos themeselves change depending on the theme. I'm not sure how it works, either the SVGs themselves have adaptive CSS inside, or this popup changes the logo URL depending on the theme.

**Comment by katspaugh** [comment] 2024-02-28 07:23
It’s a part of a library called web3-onboard. The icons come from the packages of that library.

**Comment by Akhaled19** [comment] 2024-03-02 22:47
Hi @katspaugh, thank you for the guidance! I've started working on this issue but encountered a roadblock. When running the app locally, not all UI features are supported, including the `Connect Wallet` button on the welcome landing page `http://localhost:3000/welcome`. I'm testing it on Chrome and ensured my .env file matches the variables listed [here](https://github.com/safe-global/safe-wallet-web/blob/dev/README.md#environment-variables.). I also confirmed that my popups aren't disabled. Please let me know if there's a key part of the setup that I'm missing.

**Comment by katspaugh** [comment] 2024-03-04 07:05
A valid Infira token in the env vars be enough to display the wallet popup.

**Comment by TanyaEfremova** [comment] 2024-03-19 15:16
It seems that this logo is outdated, though (see their [website](https://keyst.one/)).  For the button we can use the icon below. Do we control the logos in the blocknative modal @katspaugh ?
<img width="24" alt="logo-keystone" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/a843bda2-2a21-491c-ad34-4ba9a8468e1a">

**Comment by katspaugh** [comment] 2024-03-19 15:20
Not sure if we can override [blocknative's icon](https://github.com/blocknative/web3-onboard/blob/develop/packages/keystone/src/icon.ts) but we can make a pull request to their repo.

**Comment by katspaugh** [comment] 2024-08-08 09:50
I've updated the Keystone plugin but the icon is still the same. Closing as wontfix because the effort is not proportional to the result.

**Closed by katspaugh** 2024-08-08 09:50 UTC
Labels: bug, good first issue, minor
