### ISSUE TITLE
Addressbook: edit/delete record doesn't work ( the record is back in some time)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2615] opened 2023-10-11 10:50 UTC
## Bug description
edit/delete record doesn't work ( the record is back in some time)
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: any

## Steps to reproduce
 1. Go to the address book
 2.  delete any address
 3. wait for some time ( you can check the local storage and wait till it's refreshed for some reason)
 4. refresh the UI
 Current result: deleted/update record is back to the addressbook 
addresook localstorage is refreshed and the record is back

## Expected result
It should be possible to edit/delete records in the addressbook - https://drive.google.com/file/d/1IdJn7TW_6ElXgy5ckQM7f3pRhoxqDWHx/view?usp=sharing
## Obtained result

Support ticket - https://github.com/5afe/safe-support/issues/300

**Comment by katspaugh** [comment] 2023-10-11 12:19
Are you by any chance opening Safe in several tabs?

**Comment by katspaugh** [comment] 2024-01-03 16:56
Duplicate of #1986.

**Closed by katspaugh** 2024-01-03 16:56 UTC
Labels: bug
