### ISSUE TITLE
[Tx flow] Errors should be cards

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2288] opened 2023-07-13 09:42 UTC
## Bug description

The errors shown in the sign/execute areas are currently "embedded" in parent cards, but they [should be their own top-level ones](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=7118-171067&mode=design&t=nVHj2xBpCtqsgX8N-0).

## Steps to reproduce
 1. Connect to a Safe as a non-owner.
 2. Try to create a transaction.
 3. Observe the error.

## Expected result

The error is it's own "top-level" card.

## Obtained result

Errors are embedded within cards.

## Screenshots

Current:

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/5e6d2f9e-6334-4187-a11b-194467e89975)

Desired:

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/505a9eff-ba3b-4e48-a689-e232b1176399)

**Comment by ElizabethOgbee** [comment] 2023-07-25 09:45
Hi @iamacook  I'll like to work on this task

**Comment by iamacook** [comment] 2023-07-25 10:07
> Hi @iamacook I'll like to work on this task

@ElizabethOgbee, I'd suggest tackling [issues labelled as "good first issue"](https://github.com/safe-global/safe-wallet-web/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) but please feel free to open a PR.

**Comment by liliya-soroka** [comment] 2024-02-14 14:15
The issue is still relevant - https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1-7111&mode=design&t=1BX1Smn9y8gv4Wo2-4

**Comment by TanyaEfremova** [comment] 2024-03-19 11:18
I think, errors alerts should belong to the relevant places in the UI. This particular error is displayed before a user is about to confirm or execute a transaction, so it makes sense that it is a part of this block.

**Comment by katspaugh** [comment] 2024-03-19 12:57
Good point, closing then. 👍

**Closed by katspaugh** 2024-03-19 12:57 UTC
Labels: bug
