### ISSUE TITLE
Safe Wallet v1.4.1 on Arbitrum not usable on Safe Web UI

### ISSUE THREAD

**Issue by 0xad1onchain** [safe-global/safe-wallet-web#3059] opened 2024-01-02 09:25 UTC
## Bug description

Safe Wallet v1.4.1 deployed via the official singleton `0x41675C099F32341bf84BFc5382aF534df5C7461a` and safe proxy factory `0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67` on Arbitrum One with chain id 42161

Safe Wallet used for testing - `0xA8b1C021cE08953bbB213804dE999cE197956906`

## Potential Fix
Merging this PR to add arbitrum safe contract deployments and releasing updated package 
https://github.com/safe-global/safe-deployments/pull/344

Bumping safe-deployments package version in safe-wallet-web

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Arbitrum One

## Steps to reproduce
 1. Impersonate any Safe 1.4.1 owner wallet, in this instance can impersonate `0xc74d4Ebaa21e17D45C81AD06E932148727838660` on Arbitrum chain
 2. Try loading the existing safe wallet  `0xA8b1C021cE08953bbB213804dE999cE197956906` or any safe v1.4.1 wallet 
 
## Expected result

Should be able to add send token transactions to the safe wallet

## Obtained result

Unable to add any transactions, Safe UI doesn't recognize any token holdings to add transfer transaction

## Screenshots

Safe UI expressing incompatibility
<img width="350" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/14832564/b80f9684-016f-421d-9f47-44bd5e1f9370">

No tokens populating on the token dropdown
<img width="716" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/14832564/74fa0803-5fb5-4cb0-a866-010239c4dc19">

**Comment by katspaugh** [comment] 2024-01-03 15:49
@0xad1onchain thanks for the report and updating safe-deployments!

Apart from the frontend, that package needs to be updated in the [safe-core-sdk](https://github.com/safe-global/safe-core-sdk/tree/legacy-safe-core-sdk) as well, and the version thereof updated in this repo as well.

**Comment by Bapi-Reddy** [comment] 2024-01-08 18:10
Hey seems like the `safe-core-sdk` update to `protocol-kit` will be long one, can't the version be bumped up before that. Other than version upgrade are there any changes required to support safe 1.4.1 though ?

**Comment by katspaugh** [comment] 2024-01-08 18:27
Feel free to do, it might work. We’ll be happy to review a PR.

**Comment by 0xad1onchain** [comment] 2024-01-09 06:04
> Feel free to do, it might work. We’ll be happy to review a PR.

Could you create a new safe deployments release? Since its been a month since last release, a new version is due soon anyways

**Comment by katspaugh** [comment] 2024-01-09 07:24
@mmv08 could you release safe-deployments?

**Comment by mmv08** [comment] 2024-01-09 10:44
> @mmv08 could you release safe-deployments?

done sir

**Comment by katspaugh** [comment] 2024-02-06 16:57
Closing as a duplicate of #2558. Once that one is resolved, Arbitrum will be supported out of the box.

**Closed by katspaugh** 2024-02-06 16:57 UTC
Labels: bug
