### ISSUE TITLE
Counterfactual Safe on Base ended up with unnofficial L1 contract 

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-wallet-web#3812] opened 2024-06-07 18:02 UTC
## Bug description

User reported that they counterfactually created Safe on Base. After deploying and receiving some ETH, they tried to transfer the ETH out and received the unsupported base contract error. Turns out the Safe got deployed with the L1 contract using the mainnet L1 contract deployment address instead of our official L1 Base contract deployment. 

Safe: https://app.safe.global/home?safe=base:0x879D41d53c33F43B0CF31e909A2d3F1C2eb2cf80
Proxy: https://basescan.org/address/0x879D41d53c33F43B0CF31e909A2d3F1C2eb2cf80
Singleton: https://basescan.org/address/0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552

## Environment
 - Browser: Brave Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (x86_64)
 - Wallet: Metamask
 - Chain: Base

## Steps to reproduce
need to find out

## Expected result
L2 Safe following official deployments

## Screenshots
<img width="277" alt="Screenshot 2024-06-07 at 19 01 16" src="https://github.com/safe-global/safe-wallet-web/assets/93598450/7dfee31c-33b0-4f06-9857-faf667dcb480">

**Comment by usame-algan** [comment] 2024-06-17 15:26
I can reproduce this if I manually hard-code the chainId in `getSafeFactory` i.e. that it returns the mainnet chainId instead of the Base one: `ethersAdapter.getChainId = () => Promise.resolve(1n)`

So my guess is that this is the culprit but we need to figure out how it can happen that the chainId is not updated when activating an account.

**Comment by usame-algan** [comment] 2024-06-24 10:31
Pushed this back for now as its not clear how to arrive at this state. The way we handle it during safe creation is that we enforce that the users wallet needs to be on the same network as the safe they are about to create. That way we ensure to fetch the correct safe factory contract.

**Comment by katspaugh** [comment] 2024-06-24 10:37
Can't we use our readonly provider to fetch the contract? Also fetch from where, why?

**Comment by usame-algan** [comment] 2024-06-25 14:40
We have to call the `createProxyWithNonce` function on a specific safe factory contract. We get that contract via the protocol-kit by calling `SafeFactory.create()` with the respective `EthersAdapter`. So if the user wants to create a Safe e.g. on Sepolia we create an `EthersAdapter` with their wallet provider set to Sepolia and get the safe factory contract for Sepolia. I don't think we can use the readonly provider here since the user has to sign the transaction with their wallet.

**Comment by katspaugh** [comment] 2024-11-19 06:11
Closing as per @liliya-soroka message:

> team, I suggest to close https://github.com/safe-global/safe-wallet-web/issues/3812 , as multi-chain was implemented and we did not receive any compliance about base after it . I can not reproduce the problem

**Closed by katspaugh** 2024-11-19 06:11 UTC
Labels: bug
