### ISSUE TITLE
[1inch safe app] Transactions not going through

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2115] opened 2023-06-15 16:07 UTC
When swapping tokens via the 1inch Safe App, the UI freezes after the transaction popup is submitted.

**Comment by JagoFigueroa** [comment] 2023-06-19 15:13
I've been checking the issue reported by the 1inch team and was able to reproduce it. On gnosis chain for example, approval will get stuck and never finalise on the signTypedMessage transaction for me.

The weird thing is that prior to the signTypedMessage tx I was prompted to do a "standard" approve [transaction](https://app.safe.global/transactions/tx?safe=gno:0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A&id=multisig_0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A_0x3a0f8578a70c155a6e34c57e9f83a23c37cb9e9910eb01bb4037cb661b5e2a0c) that I was able to execute successfully and should approve the use of the token but it seems to be ignored and always forces the second signTypedMessage tx after that one.

This second signTypedMessage [transaction](https://app.safe.global/transactions/tx?safe=gno:0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A&id=multisig_0xfca7Da0a0290D7BcBEcD93bE124756fC9B6F8E6A_0xa2c950a9b93c942f489f95468c540cfdaf27e5907f4ae842d798494d53af8266) is always triggered (even after the token was already approved on the first approve tx) and although it is executable, the app will expect it every time after even if it was executed already. Plus, as reported by the 1inch team, the tx modal will get stuck on screen on execution:

https://github.com/safe-global/safe-wallet-web/assets/92332710/cc81c23f-20a3-4f6b-98ff-3e75da99cf49

Even more weird, the flow on bnb with the app of approving a swap was quite different from the one on gnosis chain (and the one on their video) and it is working as expected there for me:

https://github.com/safe-global/safe-wallet-web/assets/92332710/e2005737-1041-46b1-96e7-c5548964f413

As seen on the video it automatically batches the approve with the swap and [transaction](https://app.safe.global/transactions/tx?safe=bnb:0x1D28a316431bAFf410Fe53398c6C5BD566032Eec&id=multisig_0x1D28a316431bAFf410Fe53398c6C5BD566032Eec_0x3a27c6e7fc6ca2b4434a5d2d459f3630431f962e45f51054389a203e492f9fe1) is successful (nor does it ask for further approvals on future txs).

So, we have:

* Gnosis Chain: approve tx + signTypedMessage + swap tx?
* BNB: batched tx with approve + swap with no signTypedMessage at all

Cheers!

**Comment by katspaugh** [comment] 2023-06-19 18:18
I think you got different behaviors because 1inch is an aggregator, so it might be choosing a different contract depending on the chain and the swapped pair.

**Comment by liliya-soroka** [comment] 2024-02-14 13:54
I can not reproduce UI freezing after tx view redesign. 
Closing the issue

**Closed by liliya-soroka** 2024-02-14 13:54 UTC
Labels: bug
