### ISSUE TITLE
Hamburger icon is not left padded

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#3372] opened 2024-03-01 09:20 UTC
## Bug description

The hamburger icon in the header has none (or incorrect) `padding-left`.

## Environment
 - Browser: Firefox
 - Wallet: MetaMask
 - Chain: Polygon

## Steps to reproduce
 1. Reduce window size util sidebar is hidden.
 2. Observe incorrect padding.

## Expected result

Padding on left of hamburger icon matches that above and below it.

## Obtained result

No padding is seemingly set on the left.

## Screenshots

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/c2fb1b23-494a-406b-877a-aa69261b4c65)

**Comment by Dozie2001** [comment] 2024-03-01 12:11
@iamacook I would like to be assigned to this issue

**Comment by Dozie2001** [comment] 2024-03-02 13:22
Thank you

**Comment by Dozie2001** [comment] 2024-03-06 19:05
Having issues getting the some of the environment variables

**Comment by katspaugh** [comment] 2024-03-07 09:21
Add
```
NEXT_PUBLIC_INFURA_TOKEN=<your own api token>
```
To your .env file.

**Comment by puneetbagewadi** [comment] 2024-03-18 10:25
@katspaugh @iamacook  if this issue is still open, I can fix this.

**Comment by katspaugh** [comment] 2024-03-18 10:27
ठीक है भाई, धन्यवाद @puneetbagewadi!

**Comment by puneetbagewadi** [comment] 2024-03-18 15:04
Hi @katspaugh looks like the issue is fixed. Raising a PR

**Comment by katspaugh** [comment] 2024-03-18 15:20
Is repo mai push mat karo. Aapke fork se Pull Request karo.

**Comment by puneetbagewadi** [comment] 2024-03-18 18:48
I accidentally closed the PR  https://github.com/safe-global/safe-wallet-web/pull/3453
now its locked and I can't comment anything on that. Please reopen the PR for me to contribute. @katspaugh @iamacook

**Comment by puneetbagewadi** [comment] 2024-03-19 08:13
I have a solution for that. Let me know once you unlock the PR @katspaugh @iamacook

**Comment by katspaugh** [comment] 2024-03-19 09:29
Ab vo khula hai. 👍

**Closed** 2024-03-19 17:52 UTC
Labels: bug, good first issue
